### ISSUE TITLE
ESM module format - NestJS

### ISSUE THREAD

**Issue by andrescabrera** [nearform/mercurius-explain#343]
hi, im trying to include this plugin in a mercurious with nestJs project, but failed due to the ESM nature of the module.

I have tried to include webpack to do some transpiling to commonJs but with no luck.

There is some official guidance? Sorry if its not the appropriate channel to ask.

**Comment by simoneb** [comment]
this seems to be a limitation with NestJS unfortunately, the only option we would have is to convert this package to CJS, which we're not planning to do.

see this SO answer for some alternative options https://stackoverflow.com/a/75287028/32093
