### ISSUE TITLE
Dependency between this and the graphiql plugin

### ISSUE THREAD

**Issue by simoneb** [nearform/mercurius-explain#39]
The graphiql plugin depends on this one, because this one exposes the data that the graphiql uses:

```mermaid
graph LR
graphiql -->| uses | explain
```

Unfortunately, adding a dependency from the graphiql plugin to this one isn't feasible because the former has no way to specify dependencies. I see 2 options:

1. if we want to keep the dependency in that direction, is to version the data returned by this plugin (e.g. in a `version` property of the response), and the graphiql plugin would only process that if "semver compatible".
2. we could invert the direction of the dependency, somewhat artificially, and change this plugin's code so that when it loads the umd version of the graphiql plugin, it loads a version that's semver compatible with itself. E.g. if the version of this package is 1.2.3, it would send the query ^1 to unpkg (which supports this kind of queries)

An additional thing we should do it make [this function](https://github.com/nearform/mercurius-explain/blob/master/index.js#L51) accept an optional semver specifier, to load a specific version of the graphiql plugin from unpkg in case one wants to.

If we don't do this, we're unable to make braking changes to either this or the graphiql plugin because they're tightly coupled and there's no versioning in place.
If we do this, clearly we need more discipline in releasing them, to make sure that semver compatible versions stay compatible, plus we also introduce a temporal dependency. E.g. we can't release a major 2 of this plugin without first releasing a major 2 of the graphiql plugin (because by default this will try to load ^2 from unpkg).

It's not a win win, but I think it's worth doing.

**Comment by codeflyer** [comment]
@simoneb I like this solution, as you said is not a win win but it's a good compromise.

Picking from your comment I'll chose
* inverted direction of the dependency (the graphiql plugin rules)
* get the default value from the package.json, using  semver major
* allow to specify a version as a param in the ` explainGraphiQLPlugin` function

In addition we can return the version in the response and warn the user in case of disalignment

**Comment by simoneb** [comment]
Let's consider the timing with the blog post. If the interface of the plugin changes, we should consider waiting to publish it

**Comment by codeflyer** [comment]
The changes do not effect the blog post.
The initialization can be done with the default value, the example in the blog post is still working and is the way it should be used usually, the change of version is an edge case that we allow but it's not blog topic.

The structure returned by the plugin now adds a `version` attribute that contain the version in the package.json. This do not break the implementation and is more an information tha should be in the README.
