### ISSUE TITLE
Collect and expose data in a Federation implementation

### ISSUE THREAD

**Issue by codeflyer** [nearform/mercurius-explain#40]
The current implementation works only on a single node and do not return the data in a federated environment.

### Gateway
* exec subqueries to the services
* collect explain  information from each subgraph query
* return a structure with the augmented data

```
{
  "data": {
    "topPosts": [
      {
        "title": "Post 1"
      },
      {
        "title": "Post 2"
      }
    ]
  },
  "extensions": {
    "explain": {
      "version": "1.3.2",
      "profiler": {
        "data": [
          {
            "path": "topPosts",
            "begin": 1125340569125561,
            "end": 1125340574764765,
            "time": 5639204,
            "childExplain": {
              "service": "post",
              "data": {
                "version": "1.3.2",
                "profiler": {
                  "data": [
                    {
                      "path": "topPosts",
                      "begin": 1125340573069808,
                      "end": 1125340573217695,
                      "time": 147887
                    }
                  ]
                },
                "resolverCalls": {
                  "data": [
                    {
                      "key": "Query.topPosts",
                      "count": 1
                    }
                  ]
                }
              }
            }
          },
          {
            "path": "topPosts.0.title",
            "begin": 1125340574880451,
            "end": 1125340575050323,
            "time": 169872
          },
          {
            "path": "topPosts.1.title",
            "begin": 1125340574983056,
            "end": 1125340575098652,
            "time": 115596
          }
        ]
      },
      "resolverCalls": {
        "data": [
          {
            "key": "Query.topPosts",
            "count": 1
          },
          {
            "key": "Post.title",
            "count": 2
          }
        ]
      }
    }
  }
}
```

### Service
* Receive the request from the gateway
* check a header to enable the explain
* return the data enriched with explain information

## Issues

According on what's described above the problems to solves are:

* Add an header in the `inner` call to enable the `explain`
* Preserve the extensions data from the request and pass them in some way to the `explain` component
* Add the data to the existing structure

### Add an header in the `inner` call to enable the `explain`
This can be done different way. Ex the gateway definition allow to add headers in the request to the service.
Another way can be to enrich the header in the `preGatewayExecution` hook. (to be verified, this is the preferable way)

### Preserve the extensions data from the request and pass them in some way to the `explain` component
This step is a bit complex and now cannot be achieve because `mercurius/gateway` strips the values from the response and just return the data.

(eg.)
Service: post

query
```
query Query_topPosts {
  topPosts(count: 2) {
    title
    __typename
    pid
  }
}
```

The response is:
```
{
  data: { topPosts: [ [Object], [Object] ] },
  extensions: {
    explain: { version: '1.3.2', profiler: [Object], resolverCalls: [Object] }
  }
}
```

but the resolver in the gateway return just
```
 { topPosts: [ [Object], [Object] ] }
```

 A solution proposal can be to add this in the gateway in the `makeResolver` function.

```
const transformed = transformData(response)
      
transformed.__extensions = {...response.json.extensions || {}, __service: service.name}.  <---------
```

There is an open issue in `mercurius` https://github.com/mercurius-js/mercurius-gateway/issues/34
with an open PR that propose a different solution that can be in some way adapted to our problem.

### Add the data to the existing structure
It's enough to add `child` attribute to each entry.

**Comment by marco-ippolito** [comment]
It will be possible after: https://github.com/mercurius-js/mercurius-gateway/pull/45#pullrequestreview-1204191998 is merged
